version: '2.4'

services:
  clickbait_redis:
    image: redis:4.0.10-alpine
    container_name: clickbait-redis
    command: redis-server --requirepass a2vjPx2CJ4HcE3f323oxmG4anv
    ports:
    - 6379:6379

  content_redis:
    image: redis:4.0.10-alpine
    container_name: content-redis
    command: redis-server --requirepass a2vjPx2CJ4HcE3f323oxmG4anv
    ports:
    - 6380:6379
    expose:
    - 6379

  mongo_db:
    image: danielfuvesi/clickbait-defeater:mongo
    container_name: mongo
    ports:
    - 27017:27017

  gateway:
    image: danielfuvesi/clickbait-defeater:gateway
    container_name: clickbait-gateway
    ports:
    - 4000:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTS=-Xmx300m
    - SPRING_CLOUD_GATEWAY_ROUTES[0]_URI=http://37.252.185.74:8080
    - SPRING_CLOUD_GATEWAY_ROUTES[1]_URI=http://37.252.185.77:8080
    - SPRING_CLOUD_GATEWAY_ROUTES[2]_URI=http://37.252.185.77:8080
    - SPRING_CLOUD_GATEWAY_ROUTES[3]_URI=http://37.252.185.75:8080
    mem_limit: 367001600

  clickbait_read_service:
    image: danielfuvesi/clickbait-defeater:read-service
    container_name: clickbait-read-service
    ports:
    - 8080:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTS=-Xmx300m
    mem_limit: 367001600

  clickbait_update_service:
    image: danielfuvesi/clickbait-defeater:update-service
    container_name: clickbait-update-service
    ports:
    - 8081:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTS=-Xmx300m
    mem_limit: 367001600

  content_extraction_service:
    image: danielfuvesi/clickbait-defeater:content-extraction-service
    container_name: content-extraction-service
    ports:
    - 8082:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTS=-Xmx300m
    mem_limit: 367001600
