spring:
  profiles:
    active: dev
  redis:
    password: a2vjPx2CJ4HcE3f323oxmG4anv

logging:
  level:
    org.springframework.security: INFO

score.service:
  host: 37.252.185.77
  port: 5000

languages: en, de, es, fr, hu
