spring:
  profiles:
    active: dev
  redis:
    password: a2vjPx2CJ4HcE3f323oxmG4anv

logging:
  level:
    org.springframework.security: INFO

# If you want the detector to use every built-in language, you may replace the following property with just "all"
# Mind the possible performance impact.
languages: en, de, es, fr, hu

supported.languages: en