spring:
  redis:
    host: clickbait-redis
    port: 6379

score.service:
  protocol: http
  host: clickbait-gateway
  port: 8080

security.authorized.hosts.pattern: ^(clickbait-gateway)|(37.221.195.13)$