server:
  servlet:
    context-path: ""

spring:
  cloud:
    gateway:
      routes:
      - id: clickbait_read_score_route
        uri: http://37.252.185.74:8080
        predicates:
        - Path=/clickbait/score
        - Method=POST
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitReadFallback
      - id: clickbait_update_score_route_1
        uri: http://37.252.185.77:8080
        predicates:
        - Path=/clickbait/vote
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback
      - id: clickbait_update_score_route_2
        uri: http://37.252.185.77:8080
        predicates:
        - Path=/clickbait/votes
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback
      - id: content_extraction_route
        uri: http://37.252.185.75:8080
        predicates:
        - Path=/content/**
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/contentExtractionFallback