server:
  servlet:
    context-path: ""

security.authorized.hosts.pattern: ^(clickbait-read-service)|(clickbait-update-service)|(content-extraction-service)$

spring:
  cloud:
    gateway:
      routes:
      - id: clickbait_read_score_route
        uri: http://clickbait-read-service:8080
        predicates:
        - Path=/clickbait/score
        - Method=POST
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitReadFallback
      - id: clickbait_update_score_route_1
        uri: http://clickbait-update-service:8080
        predicates:
        - Path=/clickbait/vote
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback
      - id: clickbait_update_score_route_2
        uri: http://clickbait-update-service:8080
        predicates:
        - Path=/clickbait/votes
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback
      - id: content_extraction_route
        uri: http://content-extraction-service:8080
        predicates:
        - Path=/content/**
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/contentExtractionFallback
      - id: ml_service_precict_route
        uri: http://clickbait-classifier:5000
        predicates:
        - Path=/predict
        - Method=POST
      - id: ml_service_train_route
        uri: http://clickbait-classifier:5000
        predicates:
        - Path=/train
        - Method=POST