server:
  port: 4000
  servlet:
    context-path: ""

host: localhost

security.authorized.hosts.pattern: ^(localhost)$

spring:
  cloud:
    gateway:
      routes:
      - id: clickbait_read_score_route
        uri: http://${host}:8080
        predicates:
        - Path=/clickbait/score
        - Method=POST
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitReadFallback
      - id: clickbait_update_score_route_1
        uri: http://${host}:8081
        predicates:
        - Path=/clickbait/vote
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback
      - id: clickbait_update_score_route_2
        uri: http://${host}:8081
        predicates:
        - Path=/clickbait/votes
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback
      - id: content_extraction_route
        uri: http://${host}:8082
        predicates:
        - Path=/content/**
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/contentExtractionFallback
      - id: ml_service_precict_route
        uri: http://${host}:5000
        predicates:
        - Path=/predict
        - Method=POST
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/mlServiceFallback
      - id: ml_service_train_route
        uri: http://${host}:5000
        predicates:
        - Path=/train
        - Method=POST
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/mlServiceFallback