server:
  port: 4000
  servlet:
    context-path: ""

spring:
  cloud:
    gateway:
      routes:
      - id: clickbait_read_score_route
        uri: http://clickbait-read-service:8080
        predicates:
        - Path=/clickbait/score
        - Method=POST
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitReadFallback
      - id: clickbait_update_score_route
        uri: http://clickbait-update-service:8081
        predicates:
        - Path=/clickbait/score
        - Method=PUT
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitUpdateFallback