server:
  port: 4000
  servlet:
    context-path: ""

host: localhost

spring:
  cloud:
    gateway:
      routes:
      - id: clickbait_route
        uri: http://${host}:5000
        predicates:
        - Path=/clickbait/**
        filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/clickBaitFallback