spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      password: clickBaitServicePassword
      database: clickBaitServiceDatabase
      username: clickBaitService

content.service:
  protocol: http
  host: clickbait-gateway
  port: 8080