server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      password: clickBaitServicePassword
      database: clickBaitServiceDatabase
      username: clickBaitService

content.service:
  protocol: http
  host: localhost
  port: 4000

ml.service:
  protocol: http
  host: localhost
  port: 4000

security.authorized.hosts.pattern: ^(localhost)$