spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      password: clickBaitServicePassword
      database: clickBaitServiceDatabase
      username: clickBaitService

content.service:
  protocol: http
  host: clickbait-gateway
  port: 8080

ml.service:
  protocol: http
  host: clickbait-gateway
  port: 8080

security.authorized.hosts.pattern: ^(clickbait-gateway)|(37.221.195.13)$