spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.security: INFO


#service.relay.votes.cron: "0 0 0 * * *"
service.relay.votes.cron: "0 36 19 * * *"

ml.service:
  protocol: http
  host: 37.252.185.77
  port: 5000