/**
 * Background messaging constants
 */
const PREDICT_ARTICLE_SCORE = "PREDICT_ARTICLE_SCORE";
const VOTE_ARTICLE_SCORE = "VOTE_ARTICLE_SCORE";
const RETRIEVE_ARTICLE_SCORE_FOR_USER = "RETRIEVE_ARTICLE_SCORE_FOR_USER";
const EXTRACT_CONTENT = "EXTRACT_CONTENT";

/**
 * User relevant constants
 */
const USER_ID = "USER_ID";
