server:
  port: 8082

spring:
  redis:
    host: localhost
    port: 6380
  data:
    mongodb:
      host: localhost
      port: 27017
      password: contentExtractionServicePassword
      database: contentExtractionServiceDatabase
      username: contentExtractionService

security.authorized.hosts.pattern: ^(localhost)|(0:0:0:0:0:0:0:1)|(127.0.0.1)$