spring:
  redis:
    host: content-redis
    port: 6379
  data:
    mongodb:
      host: mongo
      port: 27017
      password: contentExtractionServicePassword
      database: contentExtractionServiceDatabase
      username: contentExtractionService

security.authorized.hosts.pattern: ^(clickbait-gateway)|(37.221.195.13)$